### ISSUE TITLE
Node failing to join without reason

### ISSUE THREAD

**Issue by patrick-bark** [victorcoder/dkron#108]
Hey, I am just getting everything setup. So I have things working very well on a single host via docker containers. However, when I attempt to expand that out to other hosts, the agent fails to join and gives no reason. My main docker-compose looks like:
```
dkron-server-luigi:
  container_name: dkron-server-luigi
  hostname: dkron-server-luigi
  links:
    - dkron-agent-luigi
  ports:
    - "8946:8946/udp"
    - "8946:8946"
    - "6868:6868/udp"
    - "6868:6868"
    - "8080:8080"
  build: ./
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config:/opt/local/dkron/config
  command: agent -server -backend=etcd -backend-machine=10.100.4.249:4001 -join=10.100.4.155:8946 -debug=true
dkron-agent-luigi:
  container_name: dkron-agent-luigi
  hostname: dkron-agent-luigi
  ports:
    - "8946"
    - "6868"
  build: ./
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config:/opt/local/dkron/config
  command: agent -debug=true -join=10.100.4.249:8946
etcd:
  image: microbox/etcd
  ports:
    - "4001:4001"
  volumes:
    - ./etcd.data:/data
  command: -name=dcron1
```

The above setup works great, but my remote agent docker-compose looks like:
```
dkron-agent-qcb1:
  container_name: dkron-agent-qcb1
  hostname: dkron-agent-qcb1
  ports:
    - "8946:8946"
    - "8946:8946/udp"
    - "6868:6868"
    - "6868:6868/udp"
  build: ./dkron
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./dkron/config:/opt/local/dkron/config
  command: agent -debug=true -join=10.100.4.249:8946
```

both are being build from the docker registry `dkron/dkron:latest`, and the error message is simply:

```
dkron-agent-qcb1 | time="2016-04-18T21:14:11Z" level=debug msg="agent: Received event" event=member-join 
dkron-agent-qcb1 | time="2016-04-18T21:14:18Z" level=debug msg="agent: Received event" event=member-failed 
```

my `dkron.json` looks like:
```
{
  "tags": {
    "role": "qcb_docker"
  },
  "keyspace": "dcron"
}
```

which is basically the same on both hosts.

I have played with all the network settings and cannot seem to find anything wrong, all of my ports are open all all protocols for both hosts. When I query the members, the remote host shows up but with a status of 4. Here is the response from that:
```
[{'Addr': '172.17.0.4',
  'DelegateCur': 4,
  'DelegateMax': 4,
  'DelegateMin': 2,
  'Name': 'dkron-server-luigi',
  'Port': 8946,
  'ProtocolCur': 2,
  'ProtocolMax': 2,
  'ProtocolMin': 1,
  'Status': 1,
  'Tags': {'key': '8f18334d9e26440bff0f3df9ad7fab6994074f8c',
   'role': 'luigi_docker',
   'server': 'true'}},
 {'Addr': '172.17.0.13',
  'DelegateCur': 4,
  'DelegateMax': 4,
  'DelegateMin': 2,
  'Name': 'dkron-agent-qcb1',
  'Port': 8946,
  'ProtocolCur': 2,
  'ProtocolMax': 2,
  'ProtocolMin': 1,
  'Status': 4,
  'Tags': {'role': 'qcb_docker'}},
 {'Addr': '172.17.0.2',
  'DelegateCur': 4,
  'DelegateMax': 4,
  'DelegateMin': 2,
  'Name': 'dkron-agent-luigi',
  'Port': 8946,
  'ProtocolCur': 2,
  'ProtocolMax': 2,
  'ProtocolMin': 1,
  'Status': 1,
  'Tags': {'role': 'luigi_docker'}}]
```

 Does anything catch your eye here?
