### ISSUE TITLE
Jobs aren't executed after restart Dkron, backed by Redis

### ISSUE THREAD

**Issue by parwin-pp** [victorcoder/dkron#416]
### docker-compose.yml
```yaml
version: '2'
services:
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    dkron:
        image: dkron/dkron:latest
        ports:
            - "8080:8080"
            - "8946"
        depends_on:
            - redis
        command: agent -server -backend=redis -backend-machine=redis:6379 -join=dkron:8946 -log-level=debug
```

## Reproduce steps
1. Start containers
```
docker-compose up
```
2. Restart containers
```
docker-compose restart
```

## Expectation
All jobs are persisted and then executed as created.

## Actual
All jobs are persisted but not executed. Both `@at` and `@every` annotation

## Investigation
When starting Dkron container, `leader` record is created with its TTL. But after restarting containers, the `leader` record still exists but does not renew until the record expired by its TTL. The Dkron agent does not try to create `leader` record again which makes all jobs not working as expected.

I have tried same reproduce steps with etcd and it does not reproduce the same result. Seems to be related to Redis factor.
