### ISSUE TITLE
Cluster discovery via -discover=name is not working 

### ISSUE THREAD

**Issue by ProPheT777** [victorcoder/dkron#421]
I'm trying to setup a cluster with auto discovery in order to get automatic scale with swarm via deploy mode global. But it's not working, and my networking have the multicast feature. 

`eth0@if849: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP`

And in the code, I didn't find any implementation of mdns, it's not implemented ? 

So my next question, 

How can I create a cluster, with one service like this : 

```yaml
    dkron:
        networks:
            - http
            - etcd
            - dkron
        entrypoint: /opt/local/dkron/dkron
        command: agent
        deploy:
            mode: global
            update_config:
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.backend=dkron"
                - "traefik.port=8080"
                - "traefik.docker.network=traefik_http"
                - "traefik.frontend.passHostHeader=true"
                - "traefik.frontend.headers.STSPreload=true"
                - "traefik.frontend.headers.STSIncludeSubdomains=true"
                - "traefik.frontend.headers.STSSeconds=31536000"
                - "traefik.frontend.headers.isDevelopment=true"
                - "traefik.frontend.headers.contentTypeNosniff=true"
                - "traefik.frontend.headers.browserXSSFilter=true"
                - "traefik.frontend.headers.frameDeny=false"
                - "traefik.frontend.headers.SSLRedirect=true"
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 30s
```

And I have this config : 

```json
{
    "backend": "etcd",
    "backend_machine": "etcd1:2379",
    "server": true,
    "debug": true,
    "log-level": "debug",
    "discover": "test",
    "tags": {
        "role": "master"
    },
    "keyspace": "dkron",
    "encrypt": "XXX"
}
```

I have also tried with 

```json
"join": [
   "dkron"
]
```

But they are isolated
